import Head from "next/head";
import MainLayout from "../components/layouts/layout";
import withAuth from "../components/layouts/withAuth";
import { useGlobalState } from "../wrapper/global";

const Home = () => {
  const { getAuthenticatedUser } = useGlobalState();
  console.log("indide index to show user => ", getAuthenticatedUser);

  return (
    <MainLayout>
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="px-6 py-8">
          <div className="flex items-center justify-between">
            <h1 className="text-3xl font-semibold tracking-wide">Overview</h1>
            <button className="px-6 py-2 text-gray-800 bg-indigo-300 rounded-lg ">
              {/* {user.name} */}
            </button>
          </div>

          <div className="mt-6 ">
            <div className="grid grid-cols-4 gap-6">
              <div className="px-6 py-4 text-gray-600 bg-pink-100 rounded-lg shadow-md">
                <h1 className="">Total On-hold Users</h1>
                <p className="pt-4 ">
                  <span className="text-5xl text-gray-800">12</span>
                  <span className="ml-4 text-sm">Users</span>
                </p>
              </div>

              <div className="px-6 py-4 text-gray-600 bg-indigo-100 rounded-lg shadow-md">
                <h1 className="">Total Active Job Posts</h1>
                <p className="pt-4 ">
                  <span className="text-5xl text-gray-800">60</span>
                  <span className="ml-4 text-sm">Posts</span>
                </p>
              </div>

              <div className="px-6 py-4 text-gray-600 bg-blue-100 rounded-lg shadow-md">
                <h1 className="">Total Applied</h1>
                <p className="pt-4 ">
                  <span className="text-5xl text-gray-800">10</span>
                  <span className="ml-4 text-sm">Candidates</span>
                </p>
                <div>
                  <p className="mt-4">
                    <span className="text-xl">10</span>% Improvement
                  </p>
                </div>
              </div>

              <div className="px-6 py-4 text-gray-600 bg-yellow-100 rounded-lg shadow-md">
                <h1 className="">Total Interviewed</h1>
                <p className="pt-4 ">
                  <span className="text-5xl text-gray-800">8</span>
                  <span className="ml-4 text-sm">Interviewees</span>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </MainLayout>
  );
};
export default withAuth(Home);
